export const OUIJA_RESPONSES = [
  "YES", "NO", "MAYBE", "SOON", "NEVER", "BEWARE", "TRUST", "WAIT",
  "LOOK WITHIN", "THE STARS ALIGN", "PATIENCE", "FATE DECIDES",
  "A DOOR OPENS", "SHADOW WATCHES", "SEEK TRUTH", "CHANGE COMES",
  "NOT YET", "BELIEVE", "DANGER", "LOVE AWAITS", "LOOK BEHIND YOU",
  "THE VEIL THINS", "ASK AGAIN", "SILENCE SPEAKS", "FOLLOW THE MOON",
  "THREE MOONS", "BLOOD REMEMBERS", "THE OLD WAYS", "LISTEN",
  "THEY KNOW", "CROSS THE RIVER", "FEAR NOT", "IT IS WRITTEN",
];
