export interface Rune {
  name: string;
  symbol: string;
  meaning: string;
  reversed: string;
  element: string;
  keywords: string[];
}

export const ELDER_FUTHARK: Rune[] = [
  { name: "Fehu", symbol: "ᚠ", meaning: "Wealth, abundance, new beginnings. Earned rewards are coming. Your efforts have not been wasted — the harvest approaches.", reversed: "Loss, greed, failure. Something you value may slip away. Are you clinging to what no longer serves?", element: "Fire", keywords: ["Wealth", "Abundance", "Success"] },
  { name: "Uruz", symbol: "ᚢ", meaning: "Strength, vitality, raw untamed power. The wild ox charges forward. You have more power than you realize — use it.", reversed: "Weakness, misdirected force, sickness. Your energy is scattered or turned against yourself.", element: "Earth", keywords: ["Strength", "Vitality", "Power"] },
  { name: "Thurisaz", symbol: "ᚦ", meaning: "Protection, the thorn, a gateway. A powerful force guards the threshold. Something requires your full attention before you pass through.", reversed: "Vulnerability, defenselessness. The thorn turns inward. Your own defenses may be wounding you.", element: "Fire", keywords: ["Protection", "Gateway", "Force"] },
  { name: "Ansuz", symbol: "ᚨ", meaning: "Divine breath, communication, wisdom from above. A message is coming — or needs to be spoken. Open your mouth and your ears.", reversed: "Miscommunication, manipulation, ignored wisdom. Someone is not telling the truth — possibly you.", element: "Air", keywords: ["Wisdom", "Communication", "Breath"] },
  { name: "Raidho", symbol: "ᚱ", meaning: "Journey, movement, the right path. The road opens before you. Trust the direction, even if you can't see the destination.", reversed: "Stagnation, wrong direction, disrupted plans. You may be on the wrong road — or refusing to move at all.", element: "Air", keywords: ["Journey", "Movement", "Rhythm"] },
  { name: "Kenaz", symbol: "ᚲ", meaning: "Torch, illumination, creativity. Something hidden becomes visible. The fire of inspiration burns through the dark.", reversed: "Darkness, confusion, creative block. The torch gutters. What are you refusing to see?", element: "Fire", keywords: ["Illumination", "Creativity", "Vision"] },
  { name: "Gebo", symbol: "ᚷ", meaning: "Gift, partnership, sacred exchange. A gift is offered — not just material but spiritual. All true gifts require reciprocity.", reversed: "Gebo has no reversed form. The gift stands as given. But ask: are you giving freely, or keeping score?", element: "Air", keywords: ["Gift", "Partnership", "Balance"] },
  { name: "Wunjo", symbol: "ᚹ", meaning: "Joy, harmony, fulfillment. A period of happiness and alignment. Allow yourself to feel it without waiting for the catch.", reversed: "Sorrow, alienation, false happiness. The joy is forced or fragile. What are you pretending to celebrate?", element: "Earth", keywords: ["Joy", "Harmony", "Fulfillment"] },
  { name: "Hagalaz", symbol: "ᚺ", meaning: "Hail, disruption, uncontrollable forces. The storm comes regardless of your plans. This destruction clears ground for new growth.", reversed: "Hagalaz has no reversed form. The hail falls as it falls. Can you find the seed inside the destruction?", element: "Water", keywords: ["Disruption", "Storm", "Transformation"] },
  { name: "Nauthiz", symbol: "ᚾ", meaning: "Need, constraint, friction. Something essential is missing. The need itself is the teacher — it shows you what you truly require.", reversed: "Unnecessary suffering, refusing to learn. You may be creating the very prison you complain about.", element: "Fire", keywords: ["Need", "Constraint", "Survival"] },
  { name: "Isa", symbol: "ᛁ", meaning: "Ice, stillness, pause. Everything is frozen. This is not death — it is preservation. Wait. Be still. The thaw will come.", reversed: "Isa has no reversed form. Ice is ice. The question is: are you using this stillness, or being paralyzed by it?", element: "Water", keywords: ["Ice", "Stillness", "Clarity"] },
  { name: "Jera", symbol: "ᛃ", meaning: "Harvest, cycles, natural reward. What you planted is ripening. This is the return on your patience. The seasons turn in your favor.", reversed: "Jera has no reversed form. The harvest comes regardless. But what exactly did you plant?", element: "Earth", keywords: ["Harvest", "Cycles", "Time"] },
  { name: "Eihwaz", symbol: "ᛇ", meaning: "Yew tree, endurance, the bridge between worlds. You stand between death and rebirth. Something is transforming at the root level.", reversed: "Eihwaz has no reversed form. The yew stands in all seasons. This transformation cannot be rushed or reversed.", element: "Earth", keywords: ["Endurance", "Death/Rebirth", "Initiation"] },
  { name: "Perthro", symbol: "ᛈ", meaning: "Mystery, fate, the unknown. The dice cup falls. Something is hidden, and its revelation will change everything. Trust the mystery.", reversed: "Stagnation, secrets, addiction. You may be hiding from your own fate, or something hidden is working against you.", element: "Water", keywords: ["Mystery", "Fate", "Hidden knowledge"] },
  { name: "Algiz", symbol: "ᛉ", meaning: "Protection, higher self, the elk sedge. You are being guarded. Your instincts are sharp right now — follow them.", reversed: "Vulnerability, hidden danger. Your guard is down, or you are ignoring a warning. Pay attention.", element: "Air", keywords: ["Protection", "Instinct", "Guardian"] },
  { name: "Sowilo", symbol: "ᛊ", meaning: "Sun, victory, wholeness. The light breaks through. Success, health, and vital energy are available. Step into your full power.", reversed: "Sowilo has no reversed form. The sun shines regardless. But are you standing in it, or hiding in the shadow?", element: "Fire", keywords: ["Sun", "Victory", "Wholeness"] },
  { name: "Tiwaz", symbol: "ᛏ", meaning: "The warrior, justice, sacrifice. A battle must be fought — internally or externally. Honor demands you act, even at a cost.", reversed: "Injustice, cowardice, imbalance. You may be avoiding a necessary confrontation or sacrificing the wrong things.", element: "Air", keywords: ["Justice", "Warrior", "Sacrifice"] },
  { name: "Berkano", symbol: "ᛒ", meaning: "Birch, birth, renewal, the feminine. New growth emerges from the dark soil. Something tender is beginning. Protect it.", reversed: "Stagnation, infertility, neglect. What new thing are you failing to nurture? Or what old thing are you forcing to live past its time?", element: "Earth", keywords: ["Birth", "Renewal", "Growth"] },
  { name: "Ehwaz", symbol: "ᛖ", meaning: "Horse, partnership, trust, movement. Two forces working together. A journey shared. Trust your partner — human, animal, or inner.", reversed: "Distrust, betrayal, stalled partnership. The bond is strained. Is the problem in the other, or in your ability to trust?", element: "Earth", keywords: ["Partnership", "Trust", "Movement"] },
  { name: "Mannaz", symbol: "ᛗ", meaning: "Humanity, self, the mind. Look at yourself clearly — without flattery or self-punishment. The human condition is your teacher now.", reversed: "Self-deception, isolation, cunning. You may be lying to yourself, or cutting yourself off from others in an unhealthy way.", element: "Air", keywords: ["Self", "Humanity", "Mind"] },
  { name: "Laguz", symbol: "ᛚ", meaning: "Water, intuition, flow, the unconscious. Go where the current takes you. Your rational mind cannot solve this — your feeling body can.", reversed: "Confusion, fear, drowning. You are fighting the current instead of reading it. Or your emotions are overwhelming your judgment.", element: "Water", keywords: ["Water", "Intuition", "Flow"] },
  { name: "Ingwaz", symbol: "ᛜ", meaning: "Seed, internal growth, potential, gestation. Something is growing inside you that is not yet ready to be born. Patience. It knows its own timing.", reversed: "Ingwaz has no reversed form. The seed grows in its own time. Your only job is not to dig it up to check.", element: "Earth", keywords: ["Seed", "Potential", "Gestation"] },
  { name: "Dagaz", symbol: "ᛞ", meaning: "Dawn, breakthrough, awakening. The long night ends. Clarity arrives suddenly. A transformation completes itself in a flash of understanding.", reversed: "Dagaz has no reversed form. Dawn comes regardless. But will you be awake for it?", element: "Fire", keywords: ["Dawn", "Breakthrough", "Clarity"] },
  { name: "Othala", symbol: "ᛟ", meaning: "Heritage, home, ancestral wisdom. What you inherit — land, blood, patterns, gifts. Your roots run deeper than you know.", reversed: "Rootlessness, family trauma, lost inheritance. You may be cut off from your lineage, or the patterns you inherited are harming you.", element: "Earth", keywords: ["Heritage", "Home", "Legacy"] },
];

export const RUNE_SPREADS: Record<string, string[]> = {
  single: ["The Message"],
  three: ["Past", "Present", "Future"],
  five: ["Situation", "Challenge", "Background", "Advice", "Outcome"],
};
